#!/bin/sh

ENABLED=yes
PROCS=skeen-box
ARGS="run -D /opt/etc/skeen -C config"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
