on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GH_PAT }}
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json

      - name: Install GitHub CLI
        run: sudo apt update && sudo apt install -y gh

      - name: Upload install.sh to release as skeen
        if: steps.release.outputs.tag != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "Release tag detected: ${{ steps.release.outputs.tag }}"
          gh release upload "${{ steps.release.outputs.tag }}" install.sh --name skeen --clobber
