on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GH_PAT }}
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json

      - name: Upload SKeen
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        run: |
          shfmt -s -mn install.sh > skeen
          gh release upload ${{ steps.release.outputs.tag_name }} skeen --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
