on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GH_PAT }}
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json

      - name: Upload Custom Asset
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release.outputs.tag_name }}
          files: |
            install.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Rename and Upload
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        run: |
          cp install.sh skeen
          gh release upload ${{ steps.release.outputs.tag_name }} skeen
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
