on:
  workflow_dispatch:

permissions:
  contents: write

name: Sync static branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare and Push to Static Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo apt install shfmt -y

          shfmt -s -mn skeen.sh > skeen_min
          shfmt -s -mn skeen_ru.sh > skeen_ru_min

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if git fetch origin static; then
            git checkout -f static
          else
            git checkout --orphan static
            git rm -rf .
          fi

          mv skeen_min skeen
          mv skeen_ru_min skeen_ru

          if [ -n "$(git status --porcelain skeen skeen_ru)" ]; then
            git add skeen skeen_ru
            git commit -m "dist: update optimized scripts $(date +'%Y-%m-%d %H:%M')"
            git push origin static

            curl -sfL "https://purge.jsdelivr.net/gh/jinndi/SKeen@static/skeen"
            curl -sfL "https://purge.jsdelivr.net/gh/jinndi/SKeen@static/skeen_ru"
          else
            echo "No changes to commit"
          fi
