on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

name: Sync static branch

jobs:
  build-and-push:
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare and Push to Static Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo apt install shfmt -y

          shfmt -s -mn skeen.sh > skeen_min
          shfmt -s -mn skeen_ru.sh > skeen_ru_min

          cp config.json config.json_tmp
          cp config_beta.json config_beta.json_tmp

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if git fetch origin static; then
            git checkout -f static
          else
            git checkout --orphan static
            git rm -rf .
          fi

          mv skeen_min skeen
          mv skeen_ru_min skeen_ru
          mv config.json_tmp config.json
          mv config_beta.json_tmp config_beta.json

          if [ -n "$(git status --porcelain skeen skeen_ru config.json config_beta.json)" ]; then
            git add skeen skeen_ru config.json config_beta.json
            git commit -m "dist: update optimized scripts and config $(date +'%Y-%m-%d %H:%M')"
            git push origin static

            for file in skeen skeen_ru config.json config_beta.json; do
              curl -sfL "https://purge.jsdelivr.net/gh/jinndi/SKeen@static/$file"
            done
          else
            echo "No changes to commit"
          fi
